// Generated by MistCSS, do not modify
import './Foo.mist.css'

import type { JSX, ReactNode } from 'react'

// Generated by MistCSS, do not modify

type FooProps = {
  children?: ReactNode;
  radius?: string;
  bg?: string;
  backgroundColor?: string;
  w?: string;
  h?: string;
  width?: string;
  height?: string;
  p?: string;
  pt?: string;
  pr?: string;
  pb?: string;
  pl?: string;
  px?: string;
  py?: string;
  padding?: string;
  m?: string;
  mt?: string;
  mb?: string;
  mr?: string;
  ml?: string;
  mx?: string;
  my?: string;
  margin?: string;
  fontSize?: string;
  fontWeight?: string;
  fontStyle?: string;
  fontFamily?: string;
  font?: string;
  color?: string;
  textAlign?: string;
  textTransform?: string;
  lineHeight?: string;
  letterSpacing?: string;
  whiteSpace?: string;
  wordBreak?: string;
  overflowWrap?: string;
  wordWrap?: string;
  hyphens?: string;
  textOrientation?: string;
  textRendering?: string;
  textSizeAdjust?: string;
  textUnderlinePosition?: string;
  textUnderlineOffset?: string;
  textUnderlineStyle?: string;
  textUnderlineColor?: string;
  textUnderline?: string;
  textOverlineStyle?: string;
  textOverlineColor?: string;
  textOverline?: string;
  textLineThroughStyle?: string;
  textLineThroughColor?: string;
  textLineThrough?: string;
  textDecorationLine?: string;
  textDecorationStyle?: string;
  textDecorationColor?: string;
  textDecoration?: string;
  textShadow?: string;
  textOverflow?: string;
  textJustify?: string;
  textIndent?: string;
  textJustifyTrim?: string;
  textAlignLast?: string;
} & JSX.IntrinsicElements['div']

// Generated by MistCSS, do not modify

export function Foo({
  children,
  radius,
  bg,
  backgroundColor,
  w,
  h,
  width,
  height,
  p,
  pt,
  pr,
  pb,
  pl,
  px,
  py,
  padding,
  m,
  mt,
  mb,
  mr,
  ml,
  mx,
  my,
  margin,
  fontSize,
  fontWeight,
  fontStyle,
  fontFamily,
  font,
  color,
  textAlign,
  textTransform,
  lineHeight,
  letterSpacing,
  whiteSpace,
  wordBreak,
  overflowWrap,
  wordWrap,
  hyphens,
  textOrientation,
  textRendering,
  textSizeAdjust,
  textUnderlinePosition,
  textUnderlineOffset,
  textUnderlineStyle,
  textUnderlineColor,
  textUnderline,
  textOverlineStyle,
  textOverlineColor,
  textOverline,
  textLineThroughStyle,
  textLineThroughColor,
  textLineThrough,
  textDecorationLine,
  textDecorationStyle,
  textDecorationColor,
  textDecoration,
  textShadow,
  textOverflow,
  textJustify,
  textIndent,
  textJustifyTrim,
  textAlignLast,
  ...props
}: FooProps) {
  return (
    <div
      {...props}
      className="foo"
      style={{
        ["--radius" as string]: radius ? `var(--radius-${radius})` : undefined,
        ["--bg" as string]: bg ? `var(--color-neutrals-${bg})` : undefined,
        ["--background-color" as string]: backgroundColor ? `var(--color-neutrals-${backgroundColor})` : undefined,
        ["--w" as string]: w ? `var(--spacing-${w})` : undefined,
        ["--h" as string]: h ? `var(--spacing-${h})` : undefined,
        ["--width" as string]: width ? `var(--spacing-${width})` : undefined,
        ["--height" as string]: height ? `var(--spacing-${height})` : undefined,
        ["--p" as string]: p ? `var(--spacing-${p})` : undefined,
        ["--pt" as string]: pt ? `var(--spacing-${pt})` : undefined,
        ["--pr" as string]: pr ? `var(--spacing-${pr})` : undefined,
        ["--pb" as string]: pb ? `var(--spacing-${pb})` : undefined,
        ["--pl" as string]: pl ? `var(--spacing-${pl})` : undefined,
        ["--px" as string]: px ? `var(--spacing-${px})` : undefined,
        ["--py" as string]: py ? `var(--spacing-${py})` : undefined,
        ["--padding" as string]: padding ? `var(--spacing-${padding})` : undefined,
        ["--m" as string]: m ? `var(--spacing-${m})` : undefined,
        ["--mt" as string]: mt ? `var(--spacing-${mt})` : undefined,
        ["--mb" as string]: mb ? `var(--spacing-${mb})` : undefined,
        ["--mr" as string]: mr ? `var(--spacing-${mr})` : undefined,
        ["--ml" as string]: ml ? `var(--spacing-${ml})` : undefined,
        ["--mx" as string]: mx ? `var(--spacing-${mx})` : undefined,
        ["--my" as string]: my ? `var(--spacing-${my})` : undefined,
        ["--margin" as string]: margin ? `var(--spacing-${margin})` : undefined,
        ["--font-size" as string]: fontSize ? `var(--font-size-${fontSize})` : undefined,
        ["--font-weight" as string]: fontWeight ? `var(--font-weight-${fontWeight})` : undefined,
        ["--font-style" as string]: fontStyle ? `var(--font-style-${fontStyle})` : undefined,
        ["--font-family" as string]: fontFamily ? `var(--font-family-${fontFamily})` : undefined,
        ["--font" as string]: font ? font : undefined,
        ["--color" as string]: color ? `var(--color-neutrals-${color})` : undefined,
        ["--text-align" as string]: textAlign ? `var(--text-align-${textAlign})` : undefined,
        ["--text-transform" as string]: textTransform ? `var(--text-transform-${textTransform})` : undefined,
        ["--line-height" as string]: lineHeight ? `var(--line-height-${lineHeight})` : undefined,
        ["--letter-spacing" as string]: letterSpacing ? `var(--letter-spacing-${letterSpacing})` : undefined,
        ["--white-space" as string]: whiteSpace ? `var(--white-space-${whiteSpace})` : undefined,
        ["--word-break" as string]: wordBreak ? `var(--word-break-${wordBreak})` : undefined,
        ["--overflow-wrap" as string]: overflowWrap ? `var(--overflow-wrap-${overflowWrap})` : undefined,
        ["--word-wrap" as string]: wordWrap ? `var(--word-wrap-${wordWrap})` : undefined,
        ["--hyphens" as string]: hyphens ? `var(--hyphens-${hyphens})` : undefined,
        ["--text-orientation" as string]: textOrientation ? `var(--text-orientation-${textOrientation})` : undefined,
        ["--text-rendering" as string]: textRendering ? `var(--text-rendering-${textRendering})` : undefined,
        ["--text-size-adjust" as string]: textSizeAdjust ? `var(--text-size-adjust-${textSizeAdjust})` : undefined,
        ["--text-underline-position" as string]: textUnderlinePosition ? `var(--text-underline-position-${textUnderlinePosition})` : undefined,
        ["--text-underline-offset" as string]: textUnderlineOffset ? `var(--text-underline-offset-${textUnderlineOffset})` : undefined,
        ["--text-underline-style" as string]: textUnderlineStyle ? `var(--text-underline-style-${textUnderlineStyle})` : undefined,
        ["--text-underline-color" as string]: textUnderlineColor ? `var(--text-underline-color-${textUnderlineColor})` : undefined,
        ["--text-underline" as string]: textUnderline ? textUnderline : undefined,
        ["--text-overline-style" as string]: textOverlineStyle ? `var(--text-overline-style-${textOverlineStyle})` : undefined,
        ["--text-overline-color" as string]: textOverlineColor ? `var(--text-overline-color-${textOverlineColor})` : undefined,
        ["--text-overline" as string]: textOverline ? textOverline : undefined,
        ["--text-line-through-style" as string]: textLineThroughStyle ? `var(--text-line-through-style-${textLineThroughStyle})` : undefined,
        ["--text-line-through-color" as string]: textLineThroughColor ? `var(--text-line-through-color-${textLineThroughColor})` : undefined,
        ["--text-line-through" as string]: textLineThrough ? textLineThrough : undefined,
        ["--text-decoration-line" as string]: textDecorationLine ? `var(--text-decoration-line-${textDecorationLine})` : undefined,
        ["--text-decoration-style" as string]: textDecorationStyle ? `var(--text-decoration-style-${textDecorationStyle})` : undefined,
        ["--text-decoration-color" as string]: textDecorationColor ? `var(--text-decoration-color-${textDecorationColor})` : undefined,
        ["--text-decoration" as string]: textDecoration ? textDecoration : undefined,
        ["--text-shadow" as string]: textShadow ? `var(--text-shadow-${textShadow})` : undefined,
        ["--text-overflow" as string]: textOverflow ? `var(--text-overflow-${textOverflow})` : undefined,
        ["--text-justify" as string]: textJustify ? `var(--text-justify-${textJustify})` : undefined,
        ["--text-indent" as string]: textIndent ? `var(--text-indent-${textIndent})` : undefined,
        ["--text-justify-trim" as string]: textJustifyTrim ? `var(--text-justify-trim-${textJustifyTrim})` : undefined,
        ["--text-align-last" as string]: textAlignLast ? `var(--text-align-last-${textAlignLast})` : undefined
      }}
    >
      {children}
    </div>
  )
}

// Generated by MistCSS, do not modify
