// Generated by MistCSS, do not modify
import './Foo.mist.css'

import type { JSX, ReactNode } from 'react'

// Generated by MistCSS, do not modify

type FooProps = {
  children?: ReactNode;
  color?: string;
  fontSize?: string;
  variant?: 'danger';
} & JSX.IntrinsicElements['div']

// Generated by MistCSS, do not modify

export function Foo({children, color, fontSize, variant, ...props }: FooProps) {
  return (
    <div
      {...props}
      className="foo"
      data-variant={variant}
      style={{
        ["--color" as string]: color ? `var(--color-${color})` : undefined,
        ["--font-size" as string]: fontSize ? `var(--font-size-${fontSize})` : undefined
      }}
    >
      {children}
    </div>
  )
}

// Generated by MistCSS, do not modify
